#!/usr/bin/env bash
PATH=/Users/murayamayuko/.nvm/versions/node/v8.1.0/bin:/Users/murayamayuko/.nvm/versions/node/v8.1.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/murayamayuko/.nvm/versions/node/v8.1.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin
git commit -m "this is a commit by gc :)" $@
